# Generated by Django 6.0.7 on 2026-08-14 13:52

import apps.customer.domain.enums.transaction_type
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_uq_account_customer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=apps.customer.domain.enums.transaction_type.TransactionType.choices, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=19)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account')),
            ],
        ),
    ]
