# Generated by Django 6.0.7 on 2026-09-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_deleted_account_trash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='closed_at',
            new_name='trashed_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opened_at',
        ),
    ]
