FROM golang:1.27-alpine

WORKDIR /app

ENV GOBIN=/usr/local/bin

RUN go install github.com/air-verse/air@latest \
	&& go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.docker.toml"]