repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args: [--fix]

      - id: ruff-format

  - repo: local
    hooks:
      - id: helm-lint
        name: Helm lint
        entry: helm lint enterprise-banking
        language: system
        pass_filenames: false
        files: ^enterprise-banking/