services:

  # -------------------------
  # Redis
  # -------------------------

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - banking


  # -------------------------
  # API Gateway
  # -------------------------

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      SERVER_ADDR: ":8080"
      LOGIN_SERVICE_URL: http://login-service:8080
      CORE_BANKING_SERVICE_URL: http://core-banking-service:8080
      REDIS_URL: redis://redis:6379
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway:/app
      - api_gateway_go_cache:/go
    command: ["air"]
    depends_on:
      redis:
        condition: service_healthy
      login-service:
        condition: service_started
      core-banking-service:
        condition: service_started
    networks:
      - banking
    restart: unless-stopped


  # -------------------------
  # Core Banking
  # -------------------------

  core-banking-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d banking"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - banking

  core-banking-migrate:
    build:
      context: ./core-banking-service
      dockerfile: Dockerfile.migration
    image: core-banking-migrate:1.0

    command:
      - "-path=/migrations" 
      - "-database=postgres://postgres:postgres@core-banking-postgres:5432/banking?sslmode=disable"
      - "up"

    depends_on:
      core-banking-postgres:
        condition: service_healthy

    networks:
      - banking

  core-banking-service:
    build:
      context: ./core-banking-service
    environment:
      DATABASE_URL: postgres://postgres:postgres@core-banking-postgres:5432/banking
      LOGIN_SERVICE_URL: http://login-service:8080
    ports:
      - "8081:8080"
    depends_on:
      core-banking-postgres:
        condition: service_healthy
      core-banking-migrate:
        condition: service_completed_successfully
      login-service:
        condition: service_started
    volumes:
      - ./core-banking-service:/app
    networks:
      - banking


  # -------------------------
  # Login
  # -------------------------

  login-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: login
      POSTGRES_USER: login
      POSTGRES_PASSWORD: login
    ports:
      - "5456:5432"
    volumes:
      - login_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U login -d login"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - banking

  login-migrate:
    image: migrate/migrate
    command:
      - "-path=/migrations"
      - "-database=postgres://login:login@login-postgres:5432/login?sslmode=disable"
      - "up"
    volumes:
      - ./login-service/migrations:/migrations
    depends_on:
      login-postgres:
        condition: service_healthy
    networks:
      - banking

  login-service:
    build:
      context: ./login-service
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgres://login:login@login-postgres:5432/login?sslmode=disable
    ports:
      - "8082:8080"
      - "2345:2345"
    volumes:
      - ./login-service:/app
      - login_go_cache:/go
    command: ["air", "-c", ".air.docker.toml"]
    depends_on:
      login-postgres:
        condition: service_healthy
      login-migrate:
        condition: service_completed_successfully
    networks:
      - banking
    restart: unless-stopped


volumes:
  postgres_data:
    external: true
    name: enterprise-banking_postgres_data

  login_postgres_data:

  login_go_cache:

  api_gateway_go_cache:

  redis_data:


networks:
  banking: