services:
  login-service:
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command:
      [
        "dlv",
        "debug",
        "--headless",
        "--listen=:40000",
        "--api-version=2",
        "--accept-multiclient",
        "--continue",
        "--log",
        "--log-output=rpc",
        "./cmd/server"
      ]
    ports:
      - "127.0.0.1:40000:40000"
    healthcheck:
      test: ["CMD-SHELL", "ps -o args | grep -q '[/]app/__debug_bin'"]
      interval: 1s
      timeout: 1s
      retries: 120
