services:

  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: banking

    ports:
      - "5454:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./scripts:/scripts

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000

    env_file:
      - .env.docker

    volumes:
      - .:/app
      - docker_venv:/app/.venv

    ports:
      - "8000:8000"

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: banking
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  docker_venv: