apiVersion: v1
kind: Pod

metadata:
  name: postgres
  labels:
    app: postgres

spec:
  containers:
    - name: postgres
      image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"

      envFrom:
        - secretRef:
            name: postgres-secret

      ports:
        - containerPort: 5432