apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: core-db
  name: core-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-db
  strategy: {}
  template:
    metadata:
      labels:
        app: core-db
    spec:
      containers:
      - image: postgres:16-alpine
        name: postgres
        resources: {}
        ports: 
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: core-banking-db-config-map
          - secretRef:
              name: core-db-secret
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
      volumes: 
      - name: db-data
        persistentVolumeClaim:
          claimName: core-db-pvc
            
status: {}
