apiVersion: v1
kind: Service
metadata:
  name: core-banking-service
  labels:
    app: core-banking-service
spec:
  type: ClusterIP
  selector:
    app: core-banking-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
