apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
        - args:
            - air
          env:
            - name: CORE_BANKING_SERVICE_URL
              value: http://core-banking-service:8080
            - name: LOGIN_SERVICE_URL
              value: http://login-service:8080
            - name: REDIS_URL
              value: redis://redis:6379
            - name: SERVER_ADDR
              value: :8080
          image: api-gateway
          name: api-gateway
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: api-gateway-cm0
            - mountPath: /go
              name: api-gateway-go-cache
      restartPolicy: Always
      volumes:
        - configMap:
            name: api-gateway-cm0
          name: api-gateway-cm0
        - name: api-gateway-go-cache
          persistentVolumeClaim:
            claimName: api-gateway-go-cache
