apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: core-banking-migrate
  name: core-banking-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: core-banking-migrate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: core-banking-migrate
    spec:
      containers:
        - args:
            - -path=/migrations
            - -database=postgres://postgres:postgres@core-banking-postgres:5432/banking?sslmode=disable
            - up
          image: migrate/migrate
          name: core-banking-migrate
          volumeMounts:
            - mountPath: /migrations
              name: core-banking-migrate-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: core-banking-migrate-cm0
          name: core-banking-migrate-cm0
