apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: core-banking-service
  name: core-banking-service
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: core-banking-service
