apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: login-postgres
  name: login-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: login-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: login
            - name: POSTGRES_PASSWORD
              value: login
            - name: POSTGRES_USER
              value: login
          image: postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U login -d login
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: login-postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: login-postgres-data
      restartPolicy: Always
      volumes:
        - name: login-postgres-data
          persistentVolumeClaim:
            claimName: login-postgres-data
