apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: login-migrate
  name: login-migrate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: login-migrate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: login-migrate
    spec:
      containers:
        - args:
            - -path=/migrations
            - -database=postgres://login:login@login-postgres:5432/login?sslmode=disable
            - up
          image: migrate/migrate
          name: login-migrate
          volumeMounts:
            - mountPath: /migrations
              name: login-migrate-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: login-migrate-cm0
          name: login-migrate-cm0
