apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: login-postgres
  name: login-postgres
spec:
  ports:
    - name: "5456"
      port: 5456
      targetPort: 5432
  selector:
    io.kompose.service: login-postgres
