# Generated by Django 6.0.7 on 2026-09-12 17:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['published', 'created_at'], name='outbox_even_publish_7c29aa_idx')],
            },
        ),
    ]
