# Generated by Django 6.0.7 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='closed_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
